name: main
on:
  push:
    branches:
      - 'feature/*'
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 20
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 20
          distribution: temurin

      - name: Install dependencies and run tests
        run: mvn test --file pom.xml
